table DimAccount
	lineageTag: e515a867-7a12-46a5-8e65-e1bce457d2b2

	column AccountKey
		dataType: int64
		formatString: 0
		lineageTag: 3a793e84-bf3f-4a01-b16c-d225e12b6ad3
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column ParentAccountKey
		dataType: int64
		formatString: 0
		lineageTag: fcbdb1d6-9eaa-4e4f-aa49-d30cd7af12e6
		summarizeBy: none
		sourceColumn: ParentAccountKey

		annotation SummarizationSetBy = Automatic

	column AccountCodeAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: d048314b-5dcf-4c8c-8264-8c32ccd37451
		summarizeBy: none
		sourceColumn: AccountCodeAlternateKey

		annotation SummarizationSetBy = Automatic

	column ParentAccountCodeAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: f128b169-a436-4fd9-a056-095731ffedb2
		summarizeBy: none
		sourceColumn: ParentAccountCodeAlternateKey

		annotation SummarizationSetBy = Automatic

	column AccountDescription
		dataType: string
		lineageTag: 166c4208-7a0b-4d59-bd93-8ebf608d29fc
		summarizeBy: none
		sourceColumn: AccountDescription

		annotation SummarizationSetBy = Automatic

	column AccountType
		dataType: string
		lineageTag: 94533973-d87f-46b7-a720-3dbb5345c168
		summarizeBy: none
		sourceColumn: AccountType

		annotation SummarizationSetBy = Automatic

	column Operator
		dataType: string
		lineageTag: 7686a100-f786-4f91-906f-0476382dad22
		summarizeBy: none
		sourceColumn: Operator

		annotation SummarizationSetBy = Automatic

	column ValueType
		dataType: string
		lineageTag: cb4bcd21-8c95-47e1-ab28-cf38742c9983
		summarizeBy: none
		sourceColumn: ValueType

		annotation SummarizationSetBy = Automatic

	column AccountHierarchyPath =
			
			PATH(
			    DimAccount[AccountKey],
			    DimAccount[ParentAccountKey]
			)
		lineageTag: 5c4caca1-6280-4396-923b-6e6d7cba2984
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AccountHierarchyLevel =
			
			PATHLENGTH(DimAccount[AccountHierarchyPath])
		formatString: 0
		lineageTag: 0cedabb7-ce37-4f56-867a-ff0ac1c3b921
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ParentAccountDescription =
			
			LOOKUPVALUE(
			    DimAccount[AccountDescription],
			    DimAccount[AccountKey],DimAccount[ParentAccountKey]
			)
		lineageTag: e0d8f4c8-1e91-49b9-b507-682318fab1ec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Root Account' =
			
			VAR RootKey =
			    PATHITEM(DimAccount[AccountHierarchyPath],1,INTEGER)
			RETURN
			    LOOKUPVALUE(
			        DimAccount[AccountDescription],
			        DimAccount[AccountKey],RootKey
			    )
		lineageTag: 2cbbc791-4a92-4146-a85d-328b12f7cb54
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'AccountCodeAlternateKey Hierarchy 2'
		lineageTag: 2c08a603-03bf-4be6-bede-db8e82d6ac32

		level 'Root Account'
			lineageTag: 22db7a13-828b-4d1c-85e5-82b57acd6c55
			column: 'Root Account'

		level ParentAccountDescription
			lineageTag: fb076d30-6381-4223-880a-e70a8ffd3461
			column: ParentAccountDescription

		level AccountDescription
			lineageTag: b9ac520d-bde5-41f1-abbe-c7755f3ae38f
			column: AccountDescription

		level AccountHierarchyLevel
			lineageTag: b08929c9-8ef4-48a1-9d49-f8385ff54284
			column: AccountHierarchyLevel

	partition DimAccount = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    AdventureWorksDW2022 = Source{[Name="AdventureWorksDW2022"]}[Data],
				    dbo_DimAccount = AdventureWorksDW2022{[Schema="dbo",Item="DimAccount"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimAccount,{"CustomMemberOptions", "CustomMembers"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

