table DimDate
	lineageTag: 7144fb09-897e-4642-93ca-91286e016e2c

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 55f5cadb-14a1-4ee6-b378-b8f879e7d571
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column FullDateAlternateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9bd8087-29b3-447b-875c-64da03c768b3
		summarizeBy: none
		sourceColumn: FullDateAlternateKey

		variation Variation
			isDefault
			relationship: 676ba1c4-bf12-4c9d-a945-9c914e131778
			defaultHierarchy: LocalDateTable_3f75419a-265a-4546-a6e4-ccb7276c946f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DayNumberOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 85cbe682-fd99-4b22-89f3-82bf51fbfd14
		summarizeBy: sum
		sourceColumn: DayNumberOfWeek

		annotation SummarizationSetBy = Automatic

	column EnglishDayNameOfWeek
		dataType: string
		lineageTag: d80d7e00-b2d4-4e91-9a06-7a83d6cdc95e
		summarizeBy: none
		sourceColumn: EnglishDayNameOfWeek

		annotation SummarizationSetBy = Automatic

	column DayNumberOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 98a5081a-3cfa-43d8-93f3-ac8c375e12f8
		summarizeBy: sum
		sourceColumn: DayNumberOfMonth

		annotation SummarizationSetBy = Automatic

	column DayNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 00bee177-f19c-483e-b98d-de96b1bec948
		summarizeBy: sum
		sourceColumn: DayNumberOfYear

		annotation SummarizationSetBy = Automatic

	column WeekNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 64a5a2e1-de74-41fc-bf5f-a2c21bb33efb
		summarizeBy: sum
		sourceColumn: WeekNumberOfYear

		annotation SummarizationSetBy = Automatic

	column EnglishMonthName
		dataType: string
		lineageTag: e574e57b-2153-4bac-a257-6992e7eb30ff
		summarizeBy: none
		sourceColumn: EnglishMonthName

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 67c67a8e-d50d-4ea6-8a3a-c70e89b328b6
		summarizeBy: sum
		sourceColumn: MonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		formatString: 0
		lineageTag: 0030a0b0-fa61-459e-80e4-cf087bbc4459
		summarizeBy: sum
		sourceColumn: CalendarQuarter

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		formatString: 0
		lineageTag: 363c21d6-61f7-4d64-9af1-5e258f135d3c
		summarizeBy: sum
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarSemester
		dataType: int64
		formatString: 0
		lineageTag: 62b573c9-4145-4f52-b00e-f824bceef398
		summarizeBy: sum
		sourceColumn: CalendarSemester

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: dfe2cf8a-6d9e-4f7c-875a-6064922ee1c2
		summarizeBy: sum
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: d710b737-299b-486a-b4bd-7c26514cc19a
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalSemester
		dataType: int64
		formatString: 0
		lineageTag: d26e1451-7387-48d3-ac1e-c40084620607
		summarizeBy: sum
		sourceColumn: FiscalSemester

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    AdventureWorksDW2022 = Source{[Name="AdventureWorksDW2022"]}[Data],
				    dbo_DimDate = AdventureWorksDW2022{[Schema="dbo",Item="DimDate"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimDate,{"SpanishDayNameOfWeek", "FrenchDayNameOfWeek", "SpanishMonthName", "FrenchMonthName"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

